# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

install! 'cocoapods',
disable_input_output_paths: true,
generate_multiple_pod_projects: true

target 'MLSCacheDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MLSCache', :path => '../'
#  pod 'YYCache'
end

target 'MLSCacheDemoTests' do
  use_frameworks!
  pod 'MLSCache', :path => '../'
#  pod 'YYCache'
end
